---

- hosts: all
  tasks:
    - name: Install Basic Desktop Packages
      become: yes
      become_user: root
      dnf:
        state: latest
        name: "{{ item }}"
      with_items:
        - thunderbird
        - keepassx
      when: ansible_os_family == 'RedHat'

    # cf. https://help.gnome.org/users/gnome-help/stable/tips-specialchars.html.en
    - name: Set Compose Key to Caps Lock
      become: yes
      become_user: root
      gsetting:
        user: "{{ ansible_user_id }}"
        key: org.gnome.desktop.input-sources.xkb-options
        value: "['compose:caps']"

    - name: Disable Switching of Keyboard Layouts
      become: yes
      become_user: root
      gsetting:
        user: "{{ ansible_user_id }}"
        key: org.gnome.desktop.wm.keybindings.switch-input-source
        value: "@as []"

    - name: Disable Switching of Keyboard Layouts (Backward)
      become: yes
      become_user: root
      gsetting:
        user: "{{ ansible_user_id }}"
        key: org.gnome.desktop.wm.keybindings.switch-input-source-backward
        value: "@as []"

    - name: Disable F10 in gnome-terminal, so that mc can use it
      become: yes
      become_user: root
      gsetting:
        user: "{{ ansible_user_id }}"
        key: org.gnome.Terminal.Legacy.Settings.menu-accelerator-enabled
        value: "false"
